#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
_____, ___
   '+ .;    
    , ;   
     .   
           
       .    
     .;.    
     .;  
      :  
      ,   
       

┌─[Vaile]─[]
└──╼ VainlyStrain
"""

import os 
import sys

script = "Vaile.py"

if len(sys.argv) > 1:
    for i in range(1, len(sys.argv)):
        script += " {}".format(sys.argv[i])
        
os.system("cd /opt/Vaile ; python3 {}".format(script))
 
